default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

sqlite: &sqlite
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary:
    <<: *default
    database: rails_cole_blog_development
    username: rails_cole_blog
    password: rails_cole_blog
  cache:
    <<: *sqlite
    database: storage/rails_cole_blog_development_cache.sqlite3
    migrations_paths: db/cache_migrate
  cable:
    <<: *sqlite
    database: storage/rails_cole_blog_development_cable.sqlite3
    migrations_paths: db/cable_migrate
  queue:
    <<: *sqlite
    database: storage/rails_cole_blog_development_queue.sqlite3
    migrations_paths: db/queue_migrate

test:
  <<: *sqlite
  database: storage/rails_cole_blog_test.sqlite3

production:
  primary: &primary_production
    <<: *default
    database: rails_cole_blog_production
    username: rails_cole_blog
    password: <%= ENV["RAILS_COLE_BLOG_DATABASE_PASSWORD"] %>
  cache:
    <<: *sqlite
    database: storage/rails_cole_blog_production_cache.sqlite3
    migrations_paths: db/cache_migrate
  cable:
    <<: *sqlite
    database: storage/rails_cole_blog_production_cable.sqlite3
    migrations_paths: db/cable_migrate
  queue:
    <<: *sqlite
    database: storage/rails_cole_blog_production_queue.sqlite3
    migrations_paths: db/queue_migrate
